apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: nginx
data:
  index.html: |
    <html>
    <head><title>Welcome</title></head>
    <body>
    <h1>Welcome to our Nginx server</h1>
    </body>
    </html>

