apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: fluent-bit
    meta.helm.sh/release-namespace: logging
    eks.amazonaws.com/role-arn: arn:aws:iam::109412806537:role/app-eks-fluent-bit
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 2.2.2
    helm.sh/chart: fluent-bit-0.43.0
  name: fluent-bit-service-account
  namespace: logging
