apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: fluent-bit
    meta.helm.sh/release-namespace: default
    eks.amazonaws.com/role-arn: arn:aws:iam::109412806537:role/app-eks-fluent-bit
  creationTimestamp: "2024-01-28T14:12:50Z"
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 2.2.2
    helm.sh/chart: fluent-bit-0.43.0
  name: fluent-bit
  namespace: default
  resourceVersion: "12113"
  uid: d6d136c7-5f82-4e90-b465-cff7c8a56c53
