apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: picture-backend-deployment
  name: picture-backend-deployment
  namespace: picture-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: picture-backend-deployment
  template:
    metadata:
      labels:
        app: picture-backend-deployment
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels: 
            app: picture-backend-deployment
      serviceAccountName: picture-backend-service-account
      containers:
      - image: 109412806537.dkr.ecr.us-east-1.amazonaws.com/app-picture-backend:135
        name: picture-backend
        envFrom:
        - secretRef:
            name: picture-backend-secret 